baseurl = "/"
languageCode = "en-us"
title = "Homepage"



[permalinks]
  # prova = "/culo"
  # try = "/gnagna"
  # porpora = "/super"
  project1 = "/project1"
  project2 = "/project6"
  project3 = "/project3"
  project4 = "/project4"
  project5 = "/project5"
  project6 = "/project6"

# [permalinks]
#   porpora = "/culo"

  # aliases = [
  #     "/post/my-original-url/",
  #     "/post/single.html"
  # ]


# [page]
#   page = "/culo"
